name: Build

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build library
        run: bazel build //C++\ Version/LISLibrary:lis_library_cpp

      - name: Build binary
        run: bazel build //C++\ Version/LIS:lis_cpp
